export type IconColorMode = "text-primary" | "original";

export const iconDefaultColor = "var(--color-text-primary)";

export const icons = {
  add: "/icons/action/add.svg",
  buy: "/icons/action/buy.svg",
  delete: "/icons/action/delete.svg",
  edit: "/icons/action/edit.svg",
  filter: "/icons/action/filter.svg",
  link: "/icons/action/link.svg",
  mailSend: "/icons/action/mail-send.svg",
  notification: "/icons/action/notification.svg",
  not: "/icons/action/not.svg",
  pause: "/icons/action/pause.svg",
  play: "/icons/action/play.svg",
  restart: "/icons/action/restart.svg",
  search: "/icons/action/search.svg",
  setting: "/icons/action/setting.svg",
  save: "/icons/action/save.svg",
  tools: "/icons/action/tools.svg",

  slide: "/icons/common/slide.svg",
  calendar: "/icons/common/calendar.svg",
  cloudOffline: "/icons/common/cloud-offline.svg",
  download: "/icons/common/download.svg",
  heart: "/icons/common/heart.svg",
  image: "/icons/common/image.svg",
  map: "/icons/common/map.svg",
  moon: "/icons/common/moon.svg",
  number1Circle: "/icons/common/number-1-circle.svg",
  number2Circle: "/icons/common/number-2-circle.svg",
  number3Circle: "/icons/common/number-3-circle.svg",
  upload: "/icons/common/upload.svg",
  dice: "/icons/common/dice.svg",
  featureFlag: "/icons/common/feature.svg",
  featureFlagDisabled: "/icons/common/feature-disabled.svg",
  target: "/icons/common/target.svg",
  scale: "/icons/common/scale.svg",
  user: "/icons/common/user.svg",
  comment: "/icons/common/comment.svg",
  arrowBack: "/icons/common/arrow-back.svg",

  eye: "/icons/input/eye.svg",
  eyeClose: "/icons/input/eye-close.svg",
  question: "/icons/input/question.svg",

  certificate: "/icons/link/certificate.svg",
  demo: "/icons/link/demo.svg",
  discord: "/icons/link/discord.svg",
  github: "/icons/link/github.svg",
  gmail: "/icons/link/gmail.svg",
  google: "/icons/link/google.svg",
  instagram: "/icons/link/instagram.svg",
  facebook: "/icons/link/facebook.svg",
  linkedin: "/icons/link/linkedin.svg",
  tiktok: "/icons/link/tiktok.svg",
  youtube: "/icons/link/youtube.svg",

  language: "/icons/language/language.svg",
  languageThai: "/icons/language/thai.svg",
  languageUs: "/icons/language/us.svg",

  about: "/icons/navigation/about.svg",
  contact: "/icons/navigation/contact.svg",
  hamburgerClose: "/icons/navigation/hamburger-close.svg",
  hamburgerOpen: "/icons/navigation/hamburger-open.svg",
  history: "/icons/navigation/history.svg",
  home: "/icons/navigation/home.svg",
  logout: "/icons/navigation/logout.svg",
  package: "/icons/navigation/package.svg",
  performance: "/icons/navigation/performance.svg",
  privacy: "/icons/navigation/privacy.svg",
  projects: "/icons/navigation/projects.svg",
  shop: "/icons/navigation/shop.svg",
  sidebarClose: "/icons/navigation/sidebar-close.svg",
  sidebarOpen: "/icons/navigation/sidebar-open.svg",
  wallet: "/icons/navigation/wallet.svg",

  directionDown: "/icons/navigation/direction/down.svg",
  directionLeft: "/icons/navigation/direction/left.svg",
  directionRight: "/icons/navigation/direction/right.svg",
  directionUp: "/icons/navigation/direction/up.svg",

  modeDark: "/icons/navigation/theme/mode-dark.svg",
  modeLight: "/icons/navigation/theme/mode-light.svg",
  modeSystem: "/icons/navigation/theme/mode-system.svg",

  shopAll: "/icons/shop/all.svg",
  shopBank: "/icons/shop/bank.svg",
  shopLog: "/icons/shop/log.svg",
  shopRenew: "/icons/shop/renew.svg",
  shopReTime: "/icons/shop/re-time.svg",
  shopRoblox: "/icons/shop/roblox.svg",
  shopServer: "/icons/shop/server.svg",
  shopStar: "/icons/shop/star.svg",
  shopTime: "/icons/shop/time.svg",
  shopVoice: "/icons/shop/voice.svg",
  shopBot: "/icons/shop/bot.svg",

  success: "/icons/status/success.svg",
  warning: "/icons/status/warning.svg",
  error: "/icons/status/error.svg",
  info: "/icons/status/info.svg",

  stack: {
    ai: {
      ai: "/icons/stack/ai/ai.svg",
      claude: "/icons/stack/ai/claude.svg",
      gemini: "/icons/stack/ai/gemini.svg",
      githubCopilot: "/icons/stack/ai/github-copilot.svg",
      lovable: "/icons/stack/ai/lovable.svg",
      meshy: "/icons/stack/ai/meshy.svg",
      openai: "/icons/stack/ai/openai.svg",
      openclaw: "/icons/stack/ai/openclaw.svg",
    },
    backend: {
      backend: "/icons/stack/backend/backend.svg",
      jwt: "/icons/stack/backend/jwt.svg",
      nodejs: "/icons/stack/backend/nodejs.svg",
      socketdotio: "/icons/stack/backend/socketdotio.svg",
      spring: "/icons/stack/backend/spring.svg",
    },
    database: {
      database: "/icons/stack/database/database.svg",
      firebase: "/icons/stack/database/firebase.svg",
      mongodb: "/icons/stack/database/mongodb.svg",
      mysql: "/icons/stack/database/mysql.svg",
      oracle: "/icons/stack/database/oracle.svg",
      postgresql: "/icons/stack/database/postgresql.svg",
      redis: "/icons/stack/database/redis.svg",
    },
    devops: {
      apacheNifi: "/icons/stack/devops/apache-nifi.svg",
      devops: "/icons/stack/devops/devops.svg",
      docker: "/icons/stack/devops/docker.svg",
      githubActions: "/icons/stack/devops/github-actions.svg",
      linux: "/icons/stack/devops/linux.svg",
      linuxServer: "/icons/stack/devops/linux-server.svg",
      maven: "/icons/stack/devops/maven.svg",
      nginx: "/icons/stack/devops/nginx.svg",
      pm2: "/icons/stack/devops/pm2.svg",
    },
    frontend: {
      bun: "/icons/stack/frontend/bun.svg",
      flutter: "/icons/stack/frontend/flutter.svg",
      frontend: "/icons/stack/frontend/frontend.svg",
      react: "/icons/stack/frontend/react.svg",
      tailwindcss: "/icons/stack/frontend/tailwindcss.svg",
      vitejs: "/icons/stack/frontend/vitejs.svg",
      vuejs: "/icons/stack/frontend/vuejs.svg",
    },
    language: {
      bashShell: "/icons/stack/language/bash-shell.svg",
      css: "/icons/stack/language/css.svg",
      dart: "/icons/stack/language/dart.svg",
      html: "/icons/stack/language/html.svg",
      java: "/icons/stack/language/java.svg",
      javascript: "/icons/stack/language/javascript.svg",
      json: "/icons/stack/language/json.svg",
      language: "/icons/stack/language/language.svg",
      lua: "/icons/stack/language/lua.svg",
      sql: "/icons/stack/language/sql.svg",
      typescript: "/icons/stack/language/typescript.svg",
      xml: "/icons/stack/language/xml.svg",
    },
    media: {
      capcut: "/icons/stack/media/capcut.svg",
      excel: "/icons/stack/media/excel.svg",
      lightroom: "/icons/stack/media/lightroom.svg",
      media: "/icons/stack/media/media.svg",
      photoshop: "/icons/stack/media/photoshop.svg",
      powerpoint: "/icons/stack/media/powerpoint.svg",
      word: "/icons/stack/media/word.svg",
    },
    service: {
      cloudinary: "/icons/stack/service/cloudinary.svg",
      externalService: "/icons/stack/service/external-service.svg",
      fileSend: "/icons/stack/service/file-send.svg",
      hardwareSecurityModule: "/icons/stack/service/hardware-security-module.svg",
      iapp: "/icons/stack/service/iapp.svg",
      openrouter: "/icons/stack/service/openrouter.svg",
      sharpEmail: "/icons/stack/service/sharp-email.svg",
      sign: "/icons/stack/service/sign.svg",
      sms: "/icons/stack/service/sms.svg",
      thaiocr: "/icons/stack/service/thaiocr.svg",
    },
    tool: {
      github: "/icons/stack/tool/github.svg",
      intellij: "/icons/stack/tool/intellij.svg",
      mysql: "/icons/stack/tool/mysql.svg",
      postman: "/icons/stack/tool/postman.svg",
      tools: "/icons/stack/tool/tools.svg",
      vscode: "/icons/stack/tool/vscode.svg",
    },
    uxUi: {
      canva: "/icons/stack/ux-ui/canva.svg",
      figma: "/icons/stack/ux-ui/figma.svg",
      uxUi: "/icons/stack/ux-ui/ux-ui.svg",
    },
  },
} as const;

const originalColorIcons = new Set<string>([
  // icons.filter,
  icons.search,
  icons.certificate,
  // icons.demo,
  icons.google,
  icons.languageThai,
  icons.languageUs,
  icons.youtube,
  icons.shopLog,
  icons.success,
  icons.warning,
  icons.error,
  icons.info,
  icons.stack.ai.claude,
  icons.stack.ai.gemini,
  icons.stack.ai.lovable,
  icons.stack.ai.meshy,
  icons.stack.ai.openai,
  icons.stack.ai.openclaw,
  icons.stack.backend.jwt,
  icons.stack.backend.nodejs,
  // icons.stack.backend.socketdotio,
  icons.stack.backend.spring,
  icons.stack.database.firebase,
  icons.stack.database.mongodb,
  icons.stack.database.mysql,
  icons.stack.database.oracle,
  icons.stack.database.postgresql,
  icons.stack.database.redis,
  icons.stack.devops.apacheNifi,
  icons.stack.devops.docker,
  icons.stack.devops.githubActions,
  icons.stack.devops.linux,
  // icons.stack.devops.linuxServer,
  icons.stack.devops.maven,
  icons.stack.devops.nginx,
  icons.stack.devops.pm2,
  icons.stack.frontend.bun,
  icons.stack.frontend.flutter,
  icons.stack.frontend.react,
  icons.stack.frontend.tailwindcss,
  icons.stack.frontend.vitejs,
  icons.stack.frontend.vuejs,
  icons.stack.language.css,
  icons.stack.language.dart,
  icons.stack.language.html,
  icons.stack.language.java,
  icons.stack.language.javascript,
  icons.stack.language.lua,
  icons.stack.language.typescript,
  icons.stack.media.excel,
  icons.stack.media.lightroom,
  icons.stack.media.photoshop,
  icons.stack.media.powerpoint,
  icons.stack.media.word,
  icons.stack.service.cloudinary,
  icons.stack.service.iapp,
  // icons.stack.service.openrouter,
  icons.stack.service.thaiocr,
  icons.stack.tool.github,
  icons.stack.tool.intellij,
  icons.stack.tool.mysql,
  icons.stack.tool.postman,
  icons.stack.tool.vscode,
  icons.stack.uxUi.canva,
  icons.stack.uxUi.figma,
]);

export function getIconColorMode(icon: string): IconColorMode {
  return originalColorIcons.has(icon) ? "original" : "text-primary";
}

export function getIconColor(icon: string): string | undefined {
  return getIconColorMode(icon) === "text-primary" ? iconDefaultColor : undefined;
}

export const shopFeatureIcons: Record<string, { label: string; src: string }> = {
  "shop-all": { label: "ทั่วไป", src: icons.shopAll },
  "shop-bank": { label: "กระเป๋าเงิน", src: icons.shopBank },
  "shop-bot": { label: "บอท", src: icons.shopBot },
  "shop-log": { label: "บันทึก", src: icons.shopLog },
  "shop-re-time": { label: "ต่อเวลา", src: icons.shopReTime },
  "shop-roblox": { label: "Roblox", src: icons.shopRoblox },
  "shop-renew": { label: "ต่ออายุ", src: icons.shopRenew },
  "shop-server": { label: "เซิร์ฟเวอร์", src: icons.shopServer },
  "shop-star": { label: "รีวิว", src: icons.shopStar },
  "shop-time": { label: "เวลา", src: icons.shopTime },
  "shop-voice": { label: "ห้องเสียง", src: icons.shopVoice },
};

export function resolveShopFeatureIcon(iconKey?: string | null): string {
  return shopFeatureIcons[iconKey ?? ""]?.src ?? icons.shopAll;
}
